# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de9eb55d7257dd9a7ece70e210b555af2a6cce9f2058fa994756047a5098b754603183fb1adf88c8d158d7f4f5467c9affac86e2c13dc4002c5aebe4b861fa1b

test:
  secret_key_base: 160c22b700f1f3d9c51282c54d3c0c33511d85ef00989d41f4c0689193ffa4ccc82eaee7a220d274825ece5694e5853410eba2a5e2ec00df8a47b294fb9eb602

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
